# Generated by Django 4.0.2 on 2022-03-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'ordering': ('-date_borrow',)},
        ),
    ]
