# Generated by Django 4.0.2 on 2022-03-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options_alter_borrowedbook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=200),
        ),
    ]
