# Generated by Django 4.0.2 on 2022-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
