# Generated by Django 4.0.2 on 2022-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_borrowedbook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
